### ISSUE TITLE
Issue with Google availability for 15526

### ISSUE THREAD

**Issue by epopov** [HostMeApp/customer-issues#6]
> Hi Marylise .can you help me fix the google page? my customers can not make reservations through google search , it shows that we are booked until four or five days.

**Link:** [Conversation with adrian salinas](https://app.intercom.com/a/apps/b0tpxtt6/respond/inbox/all/conversations/23970317550)

**Customer:** [adrian salinas](https://app.intercom.com/a/apps/b0tpxtt6/users/5d8564a46c923a07d798a519/all-conversations) from [Reyes Steakhouse](https://app.intercom.com/a/apps/b0tpxtt6/companies/5d85660d611e827fdea38a88)
**Customer ID:** 782ed287-b4d7-4c56-b271-deb3b16b8539
**Company ID:** 15526
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/b0tpxtt6/respond/inbox/all/conversations/23970317550) when this issue is closed.

**Comment by konovalov-** [comment]
He's was unmached. Have no idea how's he can see google availability.

**Comment by epopov** [comment]
I see him on Google. But only 5 days in future. Maybe he is linked to a
wrong account

**Comment by konovalov-** [comment]
I got it. He has also a restaurant 10259 and google can't match both at the same place

**Comment by epopov** [comment]
Is it easy to change the link?  Also we need to move bookings from that one

**Comment by konovalov-** [comment]
He have to delete 10259 or change the address.

**Comment by epopov** [comment]
It's probably manually creates by my crawler. I will check.
